# Base namespace for all generated files
namespace = "My.Namespace"

# Will create a subfolder within this directory with all the files
output-directory = "./Clients"

# Will override default boundry node url (like for local development)
# Only useful for generating clients from a canister id
#url = "https://localhost:8000"

# Will make generated files in a flat structure with no folders, for all clients
#no-folders = true

[[clients]]
# Defines name folder and api client class name
name = "MyClient"

# Get definition from a *.did file
type = "file"

# Path to the *.did file to use
file-path = "../MyService.did"

# Or use the following to get definition from a canister
# and remove type and file-path from above

# Get the definition from a live canister on the IC
#type = "canister"

# Canister to pull definition from
#canister-id = "rrkah-fqaaa-aaaaa-aaaaq-cai"

# Override base output directory, but this specifies the subfolder
#output-directory = "./Clients/MyS"

# Will make generated files in a flat structure with no folders, for this client
#no-folders = true
				
# Can specify multiple clients by creating another [[clients]]
#[[clients]]
#name = "MyClient2" 
#type = "file"
#file-path = "../MyService2.did"
				