name: macOS CLI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: a
        run: ls -l /usr/lib
      - name: a2
        run: ls -l /opt/homebrew/opt/gmp/lib
      - name: otool
        run: otool -L /Users/runner/work/ICP.NET/ICP.NET/src/EdjCase.Cryptography.BLS/lib/libbls384_256.dylib
      - name: Checkout submodule
        uses: Mushus/checkout-submodule@v1.0.1
        with:
          submodulePath: Fido2Net
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
