name: macOS CLI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodule
        uses: Mushus/checkout-submodule@v1.0.1
        with:
          submodulePath: Fido2Net
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build 
