name: Publish Release

on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Pack Candid
        run: dotnet pack src/Candid/Candid.csproj --configuration Release /p:Version=${{ github.event.release.tag_name }} --output .

      - name: Push Candid
        run: dotnet nuget push ICP.Candid.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
          
      - name: Pack Agent
        run: dotnet pack src/Agent/Agent.csproj --configuration Release /p:Version=${{ github.event.release.tag_name }} --output .

      - name: Push Agent
        run: dotnet nuget push ICP.Agent.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }}

      # - name: Pack Client Generator
      #   run: dotnet pack src/ClientGenerator/ClientGenerator.csproj --configuration Release /p:Version=${{ github.event.release.tag_name }} --output .

      # - name: Push Client Generator
      #   run: dotnet nuget push ICP.ClientGenerator.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }}